project:
  type: website
  output-dir: docs

website:
  title: "Echtzeit-Objekterkennung in Videostreams"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

resources:
  - models/
  - worker.js
  - videos/
  - styles.css
